
server:
  port: 2222
  servlet:
    context-path: /order

spring:
  application:
    name: order-service

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  instance:
    lease-renewal-interval-in-seconds: 1      #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 20   #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
com:
  bcy:
    username: baichuanyu
    password: 123456
    host: 12313